/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedStudioRouteRouteImport } from './routes/_authenticated/studio/route'
import { Route as AuthenticatedReceptionRouteRouteImport } from './routes/_authenticated/reception/route'
import { Route as AuthenticatedProductionRouteRouteImport } from './routes/_authenticated/production/route'
import { Route as AuthenticatedAgencyRouteRouteImport } from './routes/_authenticated/agency/route'
import { Route as AuthenticatedHubRouteRouteImport } from './routes/_authenticated/_hub/route'
import { Route as AuthenticatedStudioIndexRouteImport } from './routes/_authenticated/studio/index'
import { Route as AuthenticatedReceptionIndexRouteImport } from './routes/_authenticated/reception/index'
import { Route as AuthenticatedProductionIndexRouteImport } from './routes/_authenticated/production/index'
import { Route as AuthenticatedAgencyIndexRouteImport } from './routes/_authenticated/agency/index'
import { Route as AuthenticatedStudioTasksRouteImport } from './routes/_authenticated/studio/tasks'
import { Route as AuthenticatedStudioProgrammingRouteImport } from './routes/_authenticated/studio/programming'
import { Route as AuthenticatedStudioPhotographyRouteImport } from './routes/_authenticated/studio/photography'
import { Route as AuthenticatedStudioMontageRouteImport } from './routes/_authenticated/studio/montage'
import { Route as AuthenticatedStudioMarketingRouteImport } from './routes/_authenticated/studio/marketing'
import { Route as AuthenticatedStudioKpisRouteImport } from './routes/_authenticated/studio/kpis'
import { Route as AuthenticatedStudioDesignRouteImport } from './routes/_authenticated/studio/design'
import { Route as AuthenticatedStudioCrmRouteImport } from './routes/_authenticated/studio/crm'
import { Route as AuthenticatedStudioBookingsRouteImport } from './routes/_authenticated/studio/bookings'
import { Route as AuthenticatedStudioAccountsRouteImport } from './routes/_authenticated/studio/accounts'
import { Route as AuthenticatedReceptionPackagesRouteImport } from './routes/_authenticated/reception/packages'
import { Route as AuthenticatedReceptionCrmRouteImport } from './routes/_authenticated/reception/crm'
import { Route as AuthenticatedReceptionCashierRouteImport } from './routes/_authenticated/reception/cashier'
import { Route as AuthenticatedReceptionBookingsRouteImport } from './routes/_authenticated/reception/bookings'
import { Route as AuthenticatedProfileUserIdRouteImport } from './routes/_authenticated/profile.$userId'
import { Route as AuthenticatedProductionShootingRouteImport } from './routes/_authenticated/production/shooting'
import { Route as AuthenticatedProductionPerformanceRouteImport } from './routes/_authenticated/production/performance'
import { Route as AuthenticatedProductionMonitorRouteImport } from './routes/_authenticated/production/monitor'
import { Route as AuthenticatedProductionHistoryRouteImport } from './routes/_authenticated/production/history'
import { Route as AuthenticatedProductionExternalRouteImport } from './routes/_authenticated/production/external'
import { Route as AuthenticatedProductionEditingRouteImport } from './routes/_authenticated/production/editing'
import { Route as AuthenticatedProductionDesignRouteImport } from './routes/_authenticated/production/design'
import { Route as AuthenticatedProductionAdminRouteImport } from './routes/_authenticated/production/admin'
import { Route as AuthenticatedAgencyTasksRouteImport } from './routes/_authenticated/agency/tasks'
import { Route as AuthenticatedAgencyProjectsRouteImport } from './routes/_authenticated/agency/projects'
import { Route as AuthenticatedAgencyProgrammingRouteImport } from './routes/_authenticated/agency/programming'
import { Route as AuthenticatedAgencyPhotographyRouteImport } from './routes/_authenticated/agency/photography'
import { Route as AuthenticatedAgencyMontageRouteImport } from './routes/_authenticated/agency/montage'
import { Route as AuthenticatedAgencyDesignRouteImport } from './routes/_authenticated/agency/design'
import { Route as AuthenticatedAgencyClientsRouteImport } from './routes/_authenticated/agency/clients'
import { Route as AuthenticatedAgencyAccountsRouteImport } from './routes/_authenticated/agency/accounts'
import { Route as AuthenticatedHubUsersRouteImport } from './routes/_authenticated/_hub/users'
import { Route as AuthenticatedHubReportsRouteImport } from './routes/_authenticated/_hub/reports'
import { Route as AuthenticatedHubPackagesRouteImport } from './routes/_authenticated/_hub/packages'
import { Route as AuthenticatedHubMyTasksRouteImport } from './routes/_authenticated/_hub/my-tasks'
import { Route as AuthenticatedHubHrRouteImport } from './routes/_authenticated/_hub/hr'
import { Route as AuthenticatedHubFreelancersRouteImport } from './routes/_authenticated/_hub/freelancers'
import { Route as AuthenticatedHubDashboardRouteImport } from './routes/_authenticated/_hub/dashboard'
import { Route as AuthenticatedHubActivityRouteImport } from './routes/_authenticated/_hub/activity'
import { Route as AuthenticatedHubAccountsRouteImport } from './routes/_authenticated/_hub/accounts'
import { Route as AuthenticatedReceptionClientsIdRouteImport } from './routes/_authenticated/reception/clients.$id'
import { Route as AuthenticatedProductionTaskIdRouteImport } from './routes/_authenticated/production/task.$id'
import { Route as AuthenticatedAgencyProjectsIdRouteImport } from './routes/_authenticated/agency/projects.$id'
import { Route as AuthenticatedAgencyClientsIdRouteImport } from './routes/_authenticated/agency/clients.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioRouteRoute =
  AuthenticatedStudioRouteRouteImport.update({
    id: '/studio',
    path: '/studio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReceptionRouteRoute =
  AuthenticatedReceptionRouteRouteImport.update({
    id: '/reception',
    path: '/reception',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductionRouteRoute =
  AuthenticatedProductionRouteRouteImport.update({
    id: '/production',
    path: '/production',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgencyRouteRoute =
  AuthenticatedAgencyRouteRouteImport.update({
    id: '/agency',
    path: '/agency',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHubRouteRoute = AuthenticatedHubRouteRouteImport.update({
  id: '/_hub',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioIndexRoute =
  AuthenticatedStudioIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudioRouteRoute,
  } as any)
const AuthenticatedReceptionIndexRoute =
  AuthenticatedReceptionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReceptionRouteRoute,
  } as any)
const AuthenticatedProductionIndexRoute =
  AuthenticatedProductionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProductionRouteRoute,
  } as any)
const AuthenticatedAgencyIndexRoute =
  AuthenticatedAgencyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAgencyRouteRoute,
  } as any)
const AuthenticatedStudioTasksRoute =
  AuthenticatedStudioTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedStudioRouteRoute,
  } as any)
const AuthenticatedStudioProgrammingRoute =
  AuthenticatedStudioProgrammingRouteImport.update({
    id: '/programming',
    path: '/programming',
    getParentRoute: () => AuthenticatedStudioRouteRoute,
  } as any)
const AuthenticatedStudioPhotographyRoute =
  AuthenticatedStudioPhotographyRouteImport.update({
    id: '/photography',
    path: '/photography',
    getParentRoute: () => AuthenticatedStudioRouteRoute,
  } as any)
const AuthenticatedStudioMontageRoute =
  AuthenticatedStudioMontageRouteImport.update({
    id: '/montage',
    path: '/montage',
    getParentRoute: () => AuthenticatedStudioRouteRoute,
  } as any)
const AuthenticatedStudioMarketingRoute =
  AuthenticatedStudioMarketingRouteImport.update({
    id: '/marketing',
    path: '/marketing',
    getParentRoute: () => AuthenticatedStudioRouteRoute,
  } as any)
const AuthenticatedStudioKpisRoute = AuthenticatedStudioKpisRouteImport.update({
  id: '/kpis',
  path: '/kpis',
  getParentRoute: () => AuthenticatedStudioRouteRoute,
} as any)
const AuthenticatedStudioDesignRoute =
  AuthenticatedStudioDesignRouteImport.update({
    id: '/design',
    path: '/design',
    getParentRoute: () => AuthenticatedStudioRouteRoute,
  } as any)
const AuthenticatedStudioCrmRoute = AuthenticatedStudioCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedStudioRouteRoute,
} as any)
const AuthenticatedStudioBookingsRoute =
  AuthenticatedStudioBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedStudioRouteRoute,
  } as any)
const AuthenticatedStudioAccountsRoute =
  AuthenticatedStudioAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedStudioRouteRoute,
  } as any)
const AuthenticatedReceptionPackagesRoute =
  AuthenticatedReceptionPackagesRouteImport.update({
    id: '/packages',
    path: '/packages',
    getParentRoute: () => AuthenticatedReceptionRouteRoute,
  } as any)
const AuthenticatedReceptionCrmRoute =
  AuthenticatedReceptionCrmRouteImport.update({
    id: '/crm',
    path: '/crm',
    getParentRoute: () => AuthenticatedReceptionRouteRoute,
  } as any)
const AuthenticatedReceptionCashierRoute =
  AuthenticatedReceptionCashierRouteImport.update({
    id: '/cashier',
    path: '/cashier',
    getParentRoute: () => AuthenticatedReceptionRouteRoute,
  } as any)
const AuthenticatedReceptionBookingsRoute =
  AuthenticatedReceptionBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedReceptionRouteRoute,
  } as any)
const AuthenticatedProfileUserIdRoute =
  AuthenticatedProfileUserIdRouteImport.update({
    id: '/profile/$userId',
    path: '/profile/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductionShootingRoute =
  AuthenticatedProductionShootingRouteImport.update({
    id: '/shooting',
    path: '/shooting',
    getParentRoute: () => AuthenticatedProductionRouteRoute,
  } as any)
const AuthenticatedProductionPerformanceRoute =
  AuthenticatedProductionPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedProductionRouteRoute,
  } as any)
const AuthenticatedProductionMonitorRoute =
  AuthenticatedProductionMonitorRouteImport.update({
    id: '/monitor',
    path: '/monitor',
    getParentRoute: () => AuthenticatedProductionRouteRoute,
  } as any)
const AuthenticatedProductionHistoryRoute =
  AuthenticatedProductionHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedProductionRouteRoute,
  } as any)
const AuthenticatedProductionExternalRoute =
  AuthenticatedProductionExternalRouteImport.update({
    id: '/external',
    path: '/external',
    getParentRoute: () => AuthenticatedProductionRouteRoute,
  } as any)
const AuthenticatedProductionEditingRoute =
  AuthenticatedProductionEditingRouteImport.update({
    id: '/editing',
    path: '/editing',
    getParentRoute: () => AuthenticatedProductionRouteRoute,
  } as any)
const AuthenticatedProductionDesignRoute =
  AuthenticatedProductionDesignRouteImport.update({
    id: '/design',
    path: '/design',
    getParentRoute: () => AuthenticatedProductionRouteRoute,
  } as any)
const AuthenticatedProductionAdminRoute =
  AuthenticatedProductionAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedProductionRouteRoute,
  } as any)
const AuthenticatedAgencyTasksRoute =
  AuthenticatedAgencyTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedAgencyRouteRoute,
  } as any)
const AuthenticatedAgencyProjectsRoute =
  AuthenticatedAgencyProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAgencyRouteRoute,
  } as any)
const AuthenticatedAgencyProgrammingRoute =
  AuthenticatedAgencyProgrammingRouteImport.update({
    id: '/programming',
    path: '/programming',
    getParentRoute: () => AuthenticatedAgencyRouteRoute,
  } as any)
const AuthenticatedAgencyPhotographyRoute =
  AuthenticatedAgencyPhotographyRouteImport.update({
    id: '/photography',
    path: '/photography',
    getParentRoute: () => AuthenticatedAgencyRouteRoute,
  } as any)
const AuthenticatedAgencyMontageRoute =
  AuthenticatedAgencyMontageRouteImport.update({
    id: '/montage',
    path: '/montage',
    getParentRoute: () => AuthenticatedAgencyRouteRoute,
  } as any)
const AuthenticatedAgencyDesignRoute =
  AuthenticatedAgencyDesignRouteImport.update({
    id: '/design',
    path: '/design',
    getParentRoute: () => AuthenticatedAgencyRouteRoute,
  } as any)
const AuthenticatedAgencyClientsRoute =
  AuthenticatedAgencyClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedAgencyRouteRoute,
  } as any)
const AuthenticatedAgencyAccountsRoute =
  AuthenticatedAgencyAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedAgencyRouteRoute,
  } as any)
const AuthenticatedHubUsersRoute = AuthenticatedHubUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedHubRouteRoute,
} as any)
const AuthenticatedHubReportsRoute = AuthenticatedHubReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedHubRouteRoute,
} as any)
const AuthenticatedHubPackagesRoute =
  AuthenticatedHubPackagesRouteImport.update({
    id: '/packages',
    path: '/packages',
    getParentRoute: () => AuthenticatedHubRouteRoute,
  } as any)
const AuthenticatedHubMyTasksRoute = AuthenticatedHubMyTasksRouteImport.update({
  id: '/my-tasks',
  path: '/my-tasks',
  getParentRoute: () => AuthenticatedHubRouteRoute,
} as any)
const AuthenticatedHubHrRoute = AuthenticatedHubHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AuthenticatedHubRouteRoute,
} as any)
const AuthenticatedHubFreelancersRoute =
  AuthenticatedHubFreelancersRouteImport.update({
    id: '/freelancers',
    path: '/freelancers',
    getParentRoute: () => AuthenticatedHubRouteRoute,
  } as any)
const AuthenticatedHubDashboardRoute =
  AuthenticatedHubDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedHubRouteRoute,
  } as any)
const AuthenticatedHubActivityRoute =
  AuthenticatedHubActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedHubRouteRoute,
  } as any)
const AuthenticatedHubAccountsRoute =
  AuthenticatedHubAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedHubRouteRoute,
  } as any)
const AuthenticatedReceptionClientsIdRoute =
  AuthenticatedReceptionClientsIdRouteImport.update({
    id: '/clients/$id',
    path: '/clients/$id',
    getParentRoute: () => AuthenticatedReceptionRouteRoute,
  } as any)
const AuthenticatedProductionTaskIdRoute =
  AuthenticatedProductionTaskIdRouteImport.update({
    id: '/task/$id',
    path: '/task/$id',
    getParentRoute: () => AuthenticatedProductionRouteRoute,
  } as any)
const AuthenticatedAgencyProjectsIdRoute =
  AuthenticatedAgencyProjectsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAgencyProjectsRoute,
  } as any)
const AuthenticatedAgencyClientsIdRoute =
  AuthenticatedAgencyClientsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAgencyClientsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agency': typeof AuthenticatedAgencyRouteRouteWithChildren
  '/production': typeof AuthenticatedProductionRouteRouteWithChildren
  '/reception': typeof AuthenticatedReceptionRouteRouteWithChildren
  '/studio': typeof AuthenticatedStudioRouteRouteWithChildren
  '/me': typeof AuthenticatedMeRoute
  '/accounts': typeof AuthenticatedHubAccountsRoute
  '/activity': typeof AuthenticatedHubActivityRoute
  '/dashboard': typeof AuthenticatedHubDashboardRoute
  '/freelancers': typeof AuthenticatedHubFreelancersRoute
  '/hr': typeof AuthenticatedHubHrRoute
  '/my-tasks': typeof AuthenticatedHubMyTasksRoute
  '/packages': typeof AuthenticatedHubPackagesRoute
  '/reports': typeof AuthenticatedHubReportsRoute
  '/users': typeof AuthenticatedHubUsersRoute
  '/agency/accounts': typeof AuthenticatedAgencyAccountsRoute
  '/agency/clients': typeof AuthenticatedAgencyClientsRouteWithChildren
  '/agency/design': typeof AuthenticatedAgencyDesignRoute
  '/agency/montage': typeof AuthenticatedAgencyMontageRoute
  '/agency/photography': typeof AuthenticatedAgencyPhotographyRoute
  '/agency/programming': typeof AuthenticatedAgencyProgrammingRoute
  '/agency/projects': typeof AuthenticatedAgencyProjectsRouteWithChildren
  '/agency/tasks': typeof AuthenticatedAgencyTasksRoute
  '/production/admin': typeof AuthenticatedProductionAdminRoute
  '/production/design': typeof AuthenticatedProductionDesignRoute
  '/production/editing': typeof AuthenticatedProductionEditingRoute
  '/production/external': typeof AuthenticatedProductionExternalRoute
  '/production/history': typeof AuthenticatedProductionHistoryRoute
  '/production/monitor': typeof AuthenticatedProductionMonitorRoute
  '/production/performance': typeof AuthenticatedProductionPerformanceRoute
  '/production/shooting': typeof AuthenticatedProductionShootingRoute
  '/profile/$userId': typeof AuthenticatedProfileUserIdRoute
  '/reception/bookings': typeof AuthenticatedReceptionBookingsRoute
  '/reception/cashier': typeof AuthenticatedReceptionCashierRoute
  '/reception/crm': typeof AuthenticatedReceptionCrmRoute
  '/reception/packages': typeof AuthenticatedReceptionPackagesRoute
  '/studio/accounts': typeof AuthenticatedStudioAccountsRoute
  '/studio/bookings': typeof AuthenticatedStudioBookingsRoute
  '/studio/crm': typeof AuthenticatedStudioCrmRoute
  '/studio/design': typeof AuthenticatedStudioDesignRoute
  '/studio/kpis': typeof AuthenticatedStudioKpisRoute
  '/studio/marketing': typeof AuthenticatedStudioMarketingRoute
  '/studio/montage': typeof AuthenticatedStudioMontageRoute
  '/studio/photography': typeof AuthenticatedStudioPhotographyRoute
  '/studio/programming': typeof AuthenticatedStudioProgrammingRoute
  '/studio/tasks': typeof AuthenticatedStudioTasksRoute
  '/agency/': typeof AuthenticatedAgencyIndexRoute
  '/production/': typeof AuthenticatedProductionIndexRoute
  '/reception/': typeof AuthenticatedReceptionIndexRoute
  '/studio/': typeof AuthenticatedStudioIndexRoute
  '/agency/clients/$id': typeof AuthenticatedAgencyClientsIdRoute
  '/agency/projects/$id': typeof AuthenticatedAgencyProjectsIdRoute
  '/production/task/$id': typeof AuthenticatedProductionTaskIdRoute
  '/reception/clients/$id': typeof AuthenticatedReceptionClientsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/me': typeof AuthenticatedMeRoute
  '/accounts': typeof AuthenticatedHubAccountsRoute
  '/activity': typeof AuthenticatedHubActivityRoute
  '/dashboard': typeof AuthenticatedHubDashboardRoute
  '/freelancers': typeof AuthenticatedHubFreelancersRoute
  '/hr': typeof AuthenticatedHubHrRoute
  '/my-tasks': typeof AuthenticatedHubMyTasksRoute
  '/packages': typeof AuthenticatedHubPackagesRoute
  '/reports': typeof AuthenticatedHubReportsRoute
  '/users': typeof AuthenticatedHubUsersRoute
  '/agency/accounts': typeof AuthenticatedAgencyAccountsRoute
  '/agency/clients': typeof AuthenticatedAgencyClientsRouteWithChildren
  '/agency/design': typeof AuthenticatedAgencyDesignRoute
  '/agency/montage': typeof AuthenticatedAgencyMontageRoute
  '/agency/photography': typeof AuthenticatedAgencyPhotographyRoute
  '/agency/programming': typeof AuthenticatedAgencyProgrammingRoute
  '/agency/projects': typeof AuthenticatedAgencyProjectsRouteWithChildren
  '/agency/tasks': typeof AuthenticatedAgencyTasksRoute
  '/production/admin': typeof AuthenticatedProductionAdminRoute
  '/production/design': typeof AuthenticatedProductionDesignRoute
  '/production/editing': typeof AuthenticatedProductionEditingRoute
  '/production/external': typeof AuthenticatedProductionExternalRoute
  '/production/history': typeof AuthenticatedProductionHistoryRoute
  '/production/monitor': typeof AuthenticatedProductionMonitorRoute
  '/production/performance': typeof AuthenticatedProductionPerformanceRoute
  '/production/shooting': typeof AuthenticatedProductionShootingRoute
  '/profile/$userId': typeof AuthenticatedProfileUserIdRoute
  '/reception/bookings': typeof AuthenticatedReceptionBookingsRoute
  '/reception/cashier': typeof AuthenticatedReceptionCashierRoute
  '/reception/crm': typeof AuthenticatedReceptionCrmRoute
  '/reception/packages': typeof AuthenticatedReceptionPackagesRoute
  '/studio/accounts': typeof AuthenticatedStudioAccountsRoute
  '/studio/bookings': typeof AuthenticatedStudioBookingsRoute
  '/studio/crm': typeof AuthenticatedStudioCrmRoute
  '/studio/design': typeof AuthenticatedStudioDesignRoute
  '/studio/kpis': typeof AuthenticatedStudioKpisRoute
  '/studio/marketing': typeof AuthenticatedStudioMarketingRoute
  '/studio/montage': typeof AuthenticatedStudioMontageRoute
  '/studio/photography': typeof AuthenticatedStudioPhotographyRoute
  '/studio/programming': typeof AuthenticatedStudioProgrammingRoute
  '/studio/tasks': typeof AuthenticatedStudioTasksRoute
  '/agency': typeof AuthenticatedAgencyIndexRoute
  '/production': typeof AuthenticatedProductionIndexRoute
  '/reception': typeof AuthenticatedReceptionIndexRoute
  '/studio': typeof AuthenticatedStudioIndexRoute
  '/agency/clients/$id': typeof AuthenticatedAgencyClientsIdRoute
  '/agency/projects/$id': typeof AuthenticatedAgencyProjectsIdRoute
  '/production/task/$id': typeof AuthenticatedProductionTaskIdRoute
  '/reception/clients/$id': typeof AuthenticatedReceptionClientsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/_hub': typeof AuthenticatedHubRouteRouteWithChildren
  '/_authenticated/agency': typeof AuthenticatedAgencyRouteRouteWithChildren
  '/_authenticated/production': typeof AuthenticatedProductionRouteRouteWithChildren
  '/_authenticated/reception': typeof AuthenticatedReceptionRouteRouteWithChildren
  '/_authenticated/studio': typeof AuthenticatedStudioRouteRouteWithChildren
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/_hub/accounts': typeof AuthenticatedHubAccountsRoute
  '/_authenticated/_hub/activity': typeof AuthenticatedHubActivityRoute
  '/_authenticated/_hub/dashboard': typeof AuthenticatedHubDashboardRoute
  '/_authenticated/_hub/freelancers': typeof AuthenticatedHubFreelancersRoute
  '/_authenticated/_hub/hr': typeof AuthenticatedHubHrRoute
  '/_authenticated/_hub/my-tasks': typeof AuthenticatedHubMyTasksRoute
  '/_authenticated/_hub/packages': typeof AuthenticatedHubPackagesRoute
  '/_authenticated/_hub/reports': typeof AuthenticatedHubReportsRoute
  '/_authenticated/_hub/users': typeof AuthenticatedHubUsersRoute
  '/_authenticated/agency/accounts': typeof AuthenticatedAgencyAccountsRoute
  '/_authenticated/agency/clients': typeof AuthenticatedAgencyClientsRouteWithChildren
  '/_authenticated/agency/design': typeof AuthenticatedAgencyDesignRoute
  '/_authenticated/agency/montage': typeof AuthenticatedAgencyMontageRoute
  '/_authenticated/agency/photography': typeof AuthenticatedAgencyPhotographyRoute
  '/_authenticated/agency/programming': typeof AuthenticatedAgencyProgrammingRoute
  '/_authenticated/agency/projects': typeof AuthenticatedAgencyProjectsRouteWithChildren
  '/_authenticated/agency/tasks': typeof AuthenticatedAgencyTasksRoute
  '/_authenticated/production/admin': typeof AuthenticatedProductionAdminRoute
  '/_authenticated/production/design': typeof AuthenticatedProductionDesignRoute
  '/_authenticated/production/editing': typeof AuthenticatedProductionEditingRoute
  '/_authenticated/production/external': typeof AuthenticatedProductionExternalRoute
  '/_authenticated/production/history': typeof AuthenticatedProductionHistoryRoute
  '/_authenticated/production/monitor': typeof AuthenticatedProductionMonitorRoute
  '/_authenticated/production/performance': typeof AuthenticatedProductionPerformanceRoute
  '/_authenticated/production/shooting': typeof AuthenticatedProductionShootingRoute
  '/_authenticated/profile/$userId': typeof AuthenticatedProfileUserIdRoute
  '/_authenticated/reception/bookings': typeof AuthenticatedReceptionBookingsRoute
  '/_authenticated/reception/cashier': typeof AuthenticatedReceptionCashierRoute
  '/_authenticated/reception/crm': typeof AuthenticatedReceptionCrmRoute
  '/_authenticated/reception/packages': typeof AuthenticatedReceptionPackagesRoute
  '/_authenticated/studio/accounts': typeof AuthenticatedStudioAccountsRoute
  '/_authenticated/studio/bookings': typeof AuthenticatedStudioBookingsRoute
  '/_authenticated/studio/crm': typeof AuthenticatedStudioCrmRoute
  '/_authenticated/studio/design': typeof AuthenticatedStudioDesignRoute
  '/_authenticated/studio/kpis': typeof AuthenticatedStudioKpisRoute
  '/_authenticated/studio/marketing': typeof AuthenticatedStudioMarketingRoute
  '/_authenticated/studio/montage': typeof AuthenticatedStudioMontageRoute
  '/_authenticated/studio/photography': typeof AuthenticatedStudioPhotographyRoute
  '/_authenticated/studio/programming': typeof AuthenticatedStudioProgrammingRoute
  '/_authenticated/studio/tasks': typeof AuthenticatedStudioTasksRoute
  '/_authenticated/agency/': typeof AuthenticatedAgencyIndexRoute
  '/_authenticated/production/': typeof AuthenticatedProductionIndexRoute
  '/_authenticated/reception/': typeof AuthenticatedReceptionIndexRoute
  '/_authenticated/studio/': typeof AuthenticatedStudioIndexRoute
  '/_authenticated/agency/clients/$id': typeof AuthenticatedAgencyClientsIdRoute
  '/_authenticated/agency/projects/$id': typeof AuthenticatedAgencyProjectsIdRoute
  '/_authenticated/production/task/$id': typeof AuthenticatedProductionTaskIdRoute
  '/_authenticated/reception/clients/$id': typeof AuthenticatedReceptionClientsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agency'
    | '/production'
    | '/reception'
    | '/studio'
    | '/me'
    | '/accounts'
    | '/activity'
    | '/dashboard'
    | '/freelancers'
    | '/hr'
    | '/my-tasks'
    | '/packages'
    | '/reports'
    | '/users'
    | '/agency/accounts'
    | '/agency/clients'
    | '/agency/design'
    | '/agency/montage'
    | '/agency/photography'
    | '/agency/programming'
    | '/agency/projects'
    | '/agency/tasks'
    | '/production/admin'
    | '/production/design'
    | '/production/editing'
    | '/production/external'
    | '/production/history'
    | '/production/monitor'
    | '/production/performance'
    | '/production/shooting'
    | '/profile/$userId'
    | '/reception/bookings'
    | '/reception/cashier'
    | '/reception/crm'
    | '/reception/packages'
    | '/studio/accounts'
    | '/studio/bookings'
    | '/studio/crm'
    | '/studio/design'
    | '/studio/kpis'
    | '/studio/marketing'
    | '/studio/montage'
    | '/studio/photography'
    | '/studio/programming'
    | '/studio/tasks'
    | '/agency/'
    | '/production/'
    | '/reception/'
    | '/studio/'
    | '/agency/clients/$id'
    | '/agency/projects/$id'
    | '/production/task/$id'
    | '/reception/clients/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/me'
    | '/accounts'
    | '/activity'
    | '/dashboard'
    | '/freelancers'
    | '/hr'
    | '/my-tasks'
    | '/packages'
    | '/reports'
    | '/users'
    | '/agency/accounts'
    | '/agency/clients'
    | '/agency/design'
    | '/agency/montage'
    | '/agency/photography'
    | '/agency/programming'
    | '/agency/projects'
    | '/agency/tasks'
    | '/production/admin'
    | '/production/design'
    | '/production/editing'
    | '/production/external'
    | '/production/history'
    | '/production/monitor'
    | '/production/performance'
    | '/production/shooting'
    | '/profile/$userId'
    | '/reception/bookings'
    | '/reception/cashier'
    | '/reception/crm'
    | '/reception/packages'
    | '/studio/accounts'
    | '/studio/bookings'
    | '/studio/crm'
    | '/studio/design'
    | '/studio/kpis'
    | '/studio/marketing'
    | '/studio/montage'
    | '/studio/photography'
    | '/studio/programming'
    | '/studio/tasks'
    | '/agency'
    | '/production'
    | '/reception'
    | '/studio'
    | '/agency/clients/$id'
    | '/agency/projects/$id'
    | '/production/task/$id'
    | '/reception/clients/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_hub'
    | '/_authenticated/agency'
    | '/_authenticated/production'
    | '/_authenticated/reception'
    | '/_authenticated/studio'
    | '/_authenticated/me'
    | '/_authenticated/_hub/accounts'
    | '/_authenticated/_hub/activity'
    | '/_authenticated/_hub/dashboard'
    | '/_authenticated/_hub/freelancers'
    | '/_authenticated/_hub/hr'
    | '/_authenticated/_hub/my-tasks'
    | '/_authenticated/_hub/packages'
    | '/_authenticated/_hub/reports'
    | '/_authenticated/_hub/users'
    | '/_authenticated/agency/accounts'
    | '/_authenticated/agency/clients'
    | '/_authenticated/agency/design'
    | '/_authenticated/agency/montage'
    | '/_authenticated/agency/photography'
    | '/_authenticated/agency/programming'
    | '/_authenticated/agency/projects'
    | '/_authenticated/agency/tasks'
    | '/_authenticated/production/admin'
    | '/_authenticated/production/design'
    | '/_authenticated/production/editing'
    | '/_authenticated/production/external'
    | '/_authenticated/production/history'
    | '/_authenticated/production/monitor'
    | '/_authenticated/production/performance'
    | '/_authenticated/production/shooting'
    | '/_authenticated/profile/$userId'
    | '/_authenticated/reception/bookings'
    | '/_authenticated/reception/cashier'
    | '/_authenticated/reception/crm'
    | '/_authenticated/reception/packages'
    | '/_authenticated/studio/accounts'
    | '/_authenticated/studio/bookings'
    | '/_authenticated/studio/crm'
    | '/_authenticated/studio/design'
    | '/_authenticated/studio/kpis'
    | '/_authenticated/studio/marketing'
    | '/_authenticated/studio/montage'
    | '/_authenticated/studio/photography'
    | '/_authenticated/studio/programming'
    | '/_authenticated/studio/tasks'
    | '/_authenticated/agency/'
    | '/_authenticated/production/'
    | '/_authenticated/reception/'
    | '/_authenticated/studio/'
    | '/_authenticated/agency/clients/$id'
    | '/_authenticated/agency/projects/$id'
    | '/_authenticated/production/task/$id'
    | '/_authenticated/reception/clients/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reception': {
      id: '/_authenticated/reception'
      path: '/reception'
      fullPath: '/reception'
      preLoaderRoute: typeof AuthenticatedReceptionRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agency': {
      id: '/_authenticated/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AuthenticatedAgencyRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_hub': {
      id: '/_authenticated/_hub'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedHubRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/': {
      id: '/_authenticated/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof AuthenticatedStudioIndexRouteImport
      parentRoute: typeof AuthenticatedStudioRouteRoute
    }
    '/_authenticated/reception/': {
      id: '/_authenticated/reception/'
      path: '/'
      fullPath: '/reception/'
      preLoaderRoute: typeof AuthenticatedReceptionIndexRouteImport
      parentRoute: typeof AuthenticatedReceptionRouteRoute
    }
    '/_authenticated/production/': {
      id: '/_authenticated/production/'
      path: '/'
      fullPath: '/production/'
      preLoaderRoute: typeof AuthenticatedProductionIndexRouteImport
      parentRoute: typeof AuthenticatedProductionRouteRoute
    }
    '/_authenticated/agency/': {
      id: '/_authenticated/agency/'
      path: '/'
      fullPath: '/agency/'
      preLoaderRoute: typeof AuthenticatedAgencyIndexRouteImport
      parentRoute: typeof AuthenticatedAgencyRouteRoute
    }
    '/_authenticated/studio/tasks': {
      id: '/_authenticated/studio/tasks'
      path: '/tasks'
      fullPath: '/studio/tasks'
      preLoaderRoute: typeof AuthenticatedStudioTasksRouteImport
      parentRoute: typeof AuthenticatedStudioRouteRoute
    }
    '/_authenticated/studio/programming': {
      id: '/_authenticated/studio/programming'
      path: '/programming'
      fullPath: '/studio/programming'
      preLoaderRoute: typeof AuthenticatedStudioProgrammingRouteImport
      parentRoute: typeof AuthenticatedStudioRouteRoute
    }
    '/_authenticated/studio/photography': {
      id: '/_authenticated/studio/photography'
      path: '/photography'
      fullPath: '/studio/photography'
      preLoaderRoute: typeof AuthenticatedStudioPhotographyRouteImport
      parentRoute: typeof AuthenticatedStudioRouteRoute
    }
    '/_authenticated/studio/montage': {
      id: '/_authenticated/studio/montage'
      path: '/montage'
      fullPath: '/studio/montage'
      preLoaderRoute: typeof AuthenticatedStudioMontageRouteImport
      parentRoute: typeof AuthenticatedStudioRouteRoute
    }
    '/_authenticated/studio/marketing': {
      id: '/_authenticated/studio/marketing'
      path: '/marketing'
      fullPath: '/studio/marketing'
      preLoaderRoute: typeof AuthenticatedStudioMarketingRouteImport
      parentRoute: typeof AuthenticatedStudioRouteRoute
    }
    '/_authenticated/studio/kpis': {
      id: '/_authenticated/studio/kpis'
      path: '/kpis'
      fullPath: '/studio/kpis'
      preLoaderRoute: typeof AuthenticatedStudioKpisRouteImport
      parentRoute: typeof AuthenticatedStudioRouteRoute
    }
    '/_authenticated/studio/design': {
      id: '/_authenticated/studio/design'
      path: '/design'
      fullPath: '/studio/design'
      preLoaderRoute: typeof AuthenticatedStudioDesignRouteImport
      parentRoute: typeof AuthenticatedStudioRouteRoute
    }
    '/_authenticated/studio/crm': {
      id: '/_authenticated/studio/crm'
      path: '/crm'
      fullPath: '/studio/crm'
      preLoaderRoute: typeof AuthenticatedStudioCrmRouteImport
      parentRoute: typeof AuthenticatedStudioRouteRoute
    }
    '/_authenticated/studio/bookings': {
      id: '/_authenticated/studio/bookings'
      path: '/bookings'
      fullPath: '/studio/bookings'
      preLoaderRoute: typeof AuthenticatedStudioBookingsRouteImport
      parentRoute: typeof AuthenticatedStudioRouteRoute
    }
    '/_authenticated/studio/accounts': {
      id: '/_authenticated/studio/accounts'
      path: '/accounts'
      fullPath: '/studio/accounts'
      preLoaderRoute: typeof AuthenticatedStudioAccountsRouteImport
      parentRoute: typeof AuthenticatedStudioRouteRoute
    }
    '/_authenticated/reception/packages': {
      id: '/_authenticated/reception/packages'
      path: '/packages'
      fullPath: '/reception/packages'
      preLoaderRoute: typeof AuthenticatedReceptionPackagesRouteImport
      parentRoute: typeof AuthenticatedReceptionRouteRoute
    }
    '/_authenticated/reception/crm': {
      id: '/_authenticated/reception/crm'
      path: '/crm'
      fullPath: '/reception/crm'
      preLoaderRoute: typeof AuthenticatedReceptionCrmRouteImport
      parentRoute: typeof AuthenticatedReceptionRouteRoute
    }
    '/_authenticated/reception/cashier': {
      id: '/_authenticated/reception/cashier'
      path: '/cashier'
      fullPath: '/reception/cashier'
      preLoaderRoute: typeof AuthenticatedReceptionCashierRouteImport
      parentRoute: typeof AuthenticatedReceptionRouteRoute
    }
    '/_authenticated/reception/bookings': {
      id: '/_authenticated/reception/bookings'
      path: '/bookings'
      fullPath: '/reception/bookings'
      preLoaderRoute: typeof AuthenticatedReceptionBookingsRouteImport
      parentRoute: typeof AuthenticatedReceptionRouteRoute
    }
    '/_authenticated/profile/$userId': {
      id: '/_authenticated/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof AuthenticatedProfileUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production/shooting': {
      id: '/_authenticated/production/shooting'
      path: '/shooting'
      fullPath: '/production/shooting'
      preLoaderRoute: typeof AuthenticatedProductionShootingRouteImport
      parentRoute: typeof AuthenticatedProductionRouteRoute
    }
    '/_authenticated/production/performance': {
      id: '/_authenticated/production/performance'
      path: '/performance'
      fullPath: '/production/performance'
      preLoaderRoute: typeof AuthenticatedProductionPerformanceRouteImport
      parentRoute: typeof AuthenticatedProductionRouteRoute
    }
    '/_authenticated/production/monitor': {
      id: '/_authenticated/production/monitor'
      path: '/monitor'
      fullPath: '/production/monitor'
      preLoaderRoute: typeof AuthenticatedProductionMonitorRouteImport
      parentRoute: typeof AuthenticatedProductionRouteRoute
    }
    '/_authenticated/production/history': {
      id: '/_authenticated/production/history'
      path: '/history'
      fullPath: '/production/history'
      preLoaderRoute: typeof AuthenticatedProductionHistoryRouteImport
      parentRoute: typeof AuthenticatedProductionRouteRoute
    }
    '/_authenticated/production/external': {
      id: '/_authenticated/production/external'
      path: '/external'
      fullPath: '/production/external'
      preLoaderRoute: typeof AuthenticatedProductionExternalRouteImport
      parentRoute: typeof AuthenticatedProductionRouteRoute
    }
    '/_authenticated/production/editing': {
      id: '/_authenticated/production/editing'
      path: '/editing'
      fullPath: '/production/editing'
      preLoaderRoute: typeof AuthenticatedProductionEditingRouteImport
      parentRoute: typeof AuthenticatedProductionRouteRoute
    }
    '/_authenticated/production/design': {
      id: '/_authenticated/production/design'
      path: '/design'
      fullPath: '/production/design'
      preLoaderRoute: typeof AuthenticatedProductionDesignRouteImport
      parentRoute: typeof AuthenticatedProductionRouteRoute
    }
    '/_authenticated/production/admin': {
      id: '/_authenticated/production/admin'
      path: '/admin'
      fullPath: '/production/admin'
      preLoaderRoute: typeof AuthenticatedProductionAdminRouteImport
      parentRoute: typeof AuthenticatedProductionRouteRoute
    }
    '/_authenticated/agency/tasks': {
      id: '/_authenticated/agency/tasks'
      path: '/tasks'
      fullPath: '/agency/tasks'
      preLoaderRoute: typeof AuthenticatedAgencyTasksRouteImport
      parentRoute: typeof AuthenticatedAgencyRouteRoute
    }
    '/_authenticated/agency/projects': {
      id: '/_authenticated/agency/projects'
      path: '/projects'
      fullPath: '/agency/projects'
      preLoaderRoute: typeof AuthenticatedAgencyProjectsRouteImport
      parentRoute: typeof AuthenticatedAgencyRouteRoute
    }
    '/_authenticated/agency/programming': {
      id: '/_authenticated/agency/programming'
      path: '/programming'
      fullPath: '/agency/programming'
      preLoaderRoute: typeof AuthenticatedAgencyProgrammingRouteImport
      parentRoute: typeof AuthenticatedAgencyRouteRoute
    }
    '/_authenticated/agency/photography': {
      id: '/_authenticated/agency/photography'
      path: '/photography'
      fullPath: '/agency/photography'
      preLoaderRoute: typeof AuthenticatedAgencyPhotographyRouteImport
      parentRoute: typeof AuthenticatedAgencyRouteRoute
    }
    '/_authenticated/agency/montage': {
      id: '/_authenticated/agency/montage'
      path: '/montage'
      fullPath: '/agency/montage'
      preLoaderRoute: typeof AuthenticatedAgencyMontageRouteImport
      parentRoute: typeof AuthenticatedAgencyRouteRoute
    }
    '/_authenticated/agency/design': {
      id: '/_authenticated/agency/design'
      path: '/design'
      fullPath: '/agency/design'
      preLoaderRoute: typeof AuthenticatedAgencyDesignRouteImport
      parentRoute: typeof AuthenticatedAgencyRouteRoute
    }
    '/_authenticated/agency/clients': {
      id: '/_authenticated/agency/clients'
      path: '/clients'
      fullPath: '/agency/clients'
      preLoaderRoute: typeof AuthenticatedAgencyClientsRouteImport
      parentRoute: typeof AuthenticatedAgencyRouteRoute
    }
    '/_authenticated/agency/accounts': {
      id: '/_authenticated/agency/accounts'
      path: '/accounts'
      fullPath: '/agency/accounts'
      preLoaderRoute: typeof AuthenticatedAgencyAccountsRouteImport
      parentRoute: typeof AuthenticatedAgencyRouteRoute
    }
    '/_authenticated/_hub/users': {
      id: '/_authenticated/_hub/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedHubUsersRouteImport
      parentRoute: typeof AuthenticatedHubRouteRoute
    }
    '/_authenticated/_hub/reports': {
      id: '/_authenticated/_hub/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedHubReportsRouteImport
      parentRoute: typeof AuthenticatedHubRouteRoute
    }
    '/_authenticated/_hub/packages': {
      id: '/_authenticated/_hub/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof AuthenticatedHubPackagesRouteImport
      parentRoute: typeof AuthenticatedHubRouteRoute
    }
    '/_authenticated/_hub/my-tasks': {
      id: '/_authenticated/_hub/my-tasks'
      path: '/my-tasks'
      fullPath: '/my-tasks'
      preLoaderRoute: typeof AuthenticatedHubMyTasksRouteImport
      parentRoute: typeof AuthenticatedHubRouteRoute
    }
    '/_authenticated/_hub/hr': {
      id: '/_authenticated/_hub/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AuthenticatedHubHrRouteImport
      parentRoute: typeof AuthenticatedHubRouteRoute
    }
    '/_authenticated/_hub/freelancers': {
      id: '/_authenticated/_hub/freelancers'
      path: '/freelancers'
      fullPath: '/freelancers'
      preLoaderRoute: typeof AuthenticatedHubFreelancersRouteImport
      parentRoute: typeof AuthenticatedHubRouteRoute
    }
    '/_authenticated/_hub/dashboard': {
      id: '/_authenticated/_hub/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedHubDashboardRouteImport
      parentRoute: typeof AuthenticatedHubRouteRoute
    }
    '/_authenticated/_hub/activity': {
      id: '/_authenticated/_hub/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedHubActivityRouteImport
      parentRoute: typeof AuthenticatedHubRouteRoute
    }
    '/_authenticated/_hub/accounts': {
      id: '/_authenticated/_hub/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedHubAccountsRouteImport
      parentRoute: typeof AuthenticatedHubRouteRoute
    }
    '/_authenticated/reception/clients/$id': {
      id: '/_authenticated/reception/clients/$id'
      path: '/clients/$id'
      fullPath: '/reception/clients/$id'
      preLoaderRoute: typeof AuthenticatedReceptionClientsIdRouteImport
      parentRoute: typeof AuthenticatedReceptionRouteRoute
    }
    '/_authenticated/production/task/$id': {
      id: '/_authenticated/production/task/$id'
      path: '/task/$id'
      fullPath: '/production/task/$id'
      preLoaderRoute: typeof AuthenticatedProductionTaskIdRouteImport
      parentRoute: typeof AuthenticatedProductionRouteRoute
    }
    '/_authenticated/agency/projects/$id': {
      id: '/_authenticated/agency/projects/$id'
      path: '/$id'
      fullPath: '/agency/projects/$id'
      preLoaderRoute: typeof AuthenticatedAgencyProjectsIdRouteImport
      parentRoute: typeof AuthenticatedAgencyProjectsRoute
    }
    '/_authenticated/agency/clients/$id': {
      id: '/_authenticated/agency/clients/$id'
      path: '/$id'
      fullPath: '/agency/clients/$id'
      preLoaderRoute: typeof AuthenticatedAgencyClientsIdRouteImport
      parentRoute: typeof AuthenticatedAgencyClientsRoute
    }
  }
}

interface AuthenticatedHubRouteRouteChildren {
  AuthenticatedHubAccountsRoute: typeof AuthenticatedHubAccountsRoute
  AuthenticatedHubActivityRoute: typeof AuthenticatedHubActivityRoute
  AuthenticatedHubDashboardRoute: typeof AuthenticatedHubDashboardRoute
  AuthenticatedHubFreelancersRoute: typeof AuthenticatedHubFreelancersRoute
  AuthenticatedHubHrRoute: typeof AuthenticatedHubHrRoute
  AuthenticatedHubMyTasksRoute: typeof AuthenticatedHubMyTasksRoute
  AuthenticatedHubPackagesRoute: typeof AuthenticatedHubPackagesRoute
  AuthenticatedHubReportsRoute: typeof AuthenticatedHubReportsRoute
  AuthenticatedHubUsersRoute: typeof AuthenticatedHubUsersRoute
}

const AuthenticatedHubRouteRouteChildren: AuthenticatedHubRouteRouteChildren = {
  AuthenticatedHubAccountsRoute: AuthenticatedHubAccountsRoute,
  AuthenticatedHubActivityRoute: AuthenticatedHubActivityRoute,
  AuthenticatedHubDashboardRoute: AuthenticatedHubDashboardRoute,
  AuthenticatedHubFreelancersRoute: AuthenticatedHubFreelancersRoute,
  AuthenticatedHubHrRoute: AuthenticatedHubHrRoute,
  AuthenticatedHubMyTasksRoute: AuthenticatedHubMyTasksRoute,
  AuthenticatedHubPackagesRoute: AuthenticatedHubPackagesRoute,
  AuthenticatedHubReportsRoute: AuthenticatedHubReportsRoute,
  AuthenticatedHubUsersRoute: AuthenticatedHubUsersRoute,
}

const AuthenticatedHubRouteRouteWithChildren =
  AuthenticatedHubRouteRoute._addFileChildren(
    AuthenticatedHubRouteRouteChildren,
  )

interface AuthenticatedAgencyClientsRouteChildren {
  AuthenticatedAgencyClientsIdRoute: typeof AuthenticatedAgencyClientsIdRoute
}

const AuthenticatedAgencyClientsRouteChildren: AuthenticatedAgencyClientsRouteChildren =
  {
    AuthenticatedAgencyClientsIdRoute: AuthenticatedAgencyClientsIdRoute,
  }

const AuthenticatedAgencyClientsRouteWithChildren =
  AuthenticatedAgencyClientsRoute._addFileChildren(
    AuthenticatedAgencyClientsRouteChildren,
  )

interface AuthenticatedAgencyProjectsRouteChildren {
  AuthenticatedAgencyProjectsIdRoute: typeof AuthenticatedAgencyProjectsIdRoute
}

const AuthenticatedAgencyProjectsRouteChildren: AuthenticatedAgencyProjectsRouteChildren =
  {
    AuthenticatedAgencyProjectsIdRoute: AuthenticatedAgencyProjectsIdRoute,
  }

const AuthenticatedAgencyProjectsRouteWithChildren =
  AuthenticatedAgencyProjectsRoute._addFileChildren(
    AuthenticatedAgencyProjectsRouteChildren,
  )

interface AuthenticatedAgencyRouteRouteChildren {
  AuthenticatedAgencyAccountsRoute: typeof AuthenticatedAgencyAccountsRoute
  AuthenticatedAgencyClientsRoute: typeof AuthenticatedAgencyClientsRouteWithChildren
  AuthenticatedAgencyDesignRoute: typeof AuthenticatedAgencyDesignRoute
  AuthenticatedAgencyMontageRoute: typeof AuthenticatedAgencyMontageRoute
  AuthenticatedAgencyPhotographyRoute: typeof AuthenticatedAgencyPhotographyRoute
  AuthenticatedAgencyProgrammingRoute: typeof AuthenticatedAgencyProgrammingRoute
  AuthenticatedAgencyProjectsRoute: typeof AuthenticatedAgencyProjectsRouteWithChildren
  AuthenticatedAgencyTasksRoute: typeof AuthenticatedAgencyTasksRoute
  AuthenticatedAgencyIndexRoute: typeof AuthenticatedAgencyIndexRoute
}

const AuthenticatedAgencyRouteRouteChildren: AuthenticatedAgencyRouteRouteChildren =
  {
    AuthenticatedAgencyAccountsRoute: AuthenticatedAgencyAccountsRoute,
    AuthenticatedAgencyClientsRoute:
      AuthenticatedAgencyClientsRouteWithChildren,
    AuthenticatedAgencyDesignRoute: AuthenticatedAgencyDesignRoute,
    AuthenticatedAgencyMontageRoute: AuthenticatedAgencyMontageRoute,
    AuthenticatedAgencyPhotographyRoute: AuthenticatedAgencyPhotographyRoute,
    AuthenticatedAgencyProgrammingRoute: AuthenticatedAgencyProgrammingRoute,
    AuthenticatedAgencyProjectsRoute:
      AuthenticatedAgencyProjectsRouteWithChildren,
    AuthenticatedAgencyTasksRoute: AuthenticatedAgencyTasksRoute,
    AuthenticatedAgencyIndexRoute: AuthenticatedAgencyIndexRoute,
  }

const AuthenticatedAgencyRouteRouteWithChildren =
  AuthenticatedAgencyRouteRoute._addFileChildren(
    AuthenticatedAgencyRouteRouteChildren,
  )

interface AuthenticatedProductionRouteRouteChildren {
  AuthenticatedProductionAdminRoute: typeof AuthenticatedProductionAdminRoute
  AuthenticatedProductionDesignRoute: typeof AuthenticatedProductionDesignRoute
  AuthenticatedProductionEditingRoute: typeof AuthenticatedProductionEditingRoute
  AuthenticatedProductionExternalRoute: typeof AuthenticatedProductionExternalRoute
  AuthenticatedProductionHistoryRoute: typeof AuthenticatedProductionHistoryRoute
  AuthenticatedProductionMonitorRoute: typeof AuthenticatedProductionMonitorRoute
  AuthenticatedProductionPerformanceRoute: typeof AuthenticatedProductionPerformanceRoute
  AuthenticatedProductionShootingRoute: typeof AuthenticatedProductionShootingRoute
  AuthenticatedProductionIndexRoute: typeof AuthenticatedProductionIndexRoute
  AuthenticatedProductionTaskIdRoute: typeof AuthenticatedProductionTaskIdRoute
}

const AuthenticatedProductionRouteRouteChildren: AuthenticatedProductionRouteRouteChildren =
  {
    AuthenticatedProductionAdminRoute: AuthenticatedProductionAdminRoute,
    AuthenticatedProductionDesignRoute: AuthenticatedProductionDesignRoute,
    AuthenticatedProductionEditingRoute: AuthenticatedProductionEditingRoute,
    AuthenticatedProductionExternalRoute: AuthenticatedProductionExternalRoute,
    AuthenticatedProductionHistoryRoute: AuthenticatedProductionHistoryRoute,
    AuthenticatedProductionMonitorRoute: AuthenticatedProductionMonitorRoute,
    AuthenticatedProductionPerformanceRoute:
      AuthenticatedProductionPerformanceRoute,
    AuthenticatedProductionShootingRoute: AuthenticatedProductionShootingRoute,
    AuthenticatedProductionIndexRoute: AuthenticatedProductionIndexRoute,
    AuthenticatedProductionTaskIdRoute: AuthenticatedProductionTaskIdRoute,
  }

const AuthenticatedProductionRouteRouteWithChildren =
  AuthenticatedProductionRouteRoute._addFileChildren(
    AuthenticatedProductionRouteRouteChildren,
  )

interface AuthenticatedReceptionRouteRouteChildren {
  AuthenticatedReceptionBookingsRoute: typeof AuthenticatedReceptionBookingsRoute
  AuthenticatedReceptionCashierRoute: typeof AuthenticatedReceptionCashierRoute
  AuthenticatedReceptionCrmRoute: typeof AuthenticatedReceptionCrmRoute
  AuthenticatedReceptionPackagesRoute: typeof AuthenticatedReceptionPackagesRoute
  AuthenticatedReceptionIndexRoute: typeof AuthenticatedReceptionIndexRoute
  AuthenticatedReceptionClientsIdRoute: typeof AuthenticatedReceptionClientsIdRoute
}

const AuthenticatedReceptionRouteRouteChildren: AuthenticatedReceptionRouteRouteChildren =
  {
    AuthenticatedReceptionBookingsRoute: AuthenticatedReceptionBookingsRoute,
    AuthenticatedReceptionCashierRoute: AuthenticatedReceptionCashierRoute,
    AuthenticatedReceptionCrmRoute: AuthenticatedReceptionCrmRoute,
    AuthenticatedReceptionPackagesRoute: AuthenticatedReceptionPackagesRoute,
    AuthenticatedReceptionIndexRoute: AuthenticatedReceptionIndexRoute,
    AuthenticatedReceptionClientsIdRoute: AuthenticatedReceptionClientsIdRoute,
  }

const AuthenticatedReceptionRouteRouteWithChildren =
  AuthenticatedReceptionRouteRoute._addFileChildren(
    AuthenticatedReceptionRouteRouteChildren,
  )

interface AuthenticatedStudioRouteRouteChildren {
  AuthenticatedStudioAccountsRoute: typeof AuthenticatedStudioAccountsRoute
  AuthenticatedStudioBookingsRoute: typeof AuthenticatedStudioBookingsRoute
  AuthenticatedStudioCrmRoute: typeof AuthenticatedStudioCrmRoute
  AuthenticatedStudioDesignRoute: typeof AuthenticatedStudioDesignRoute
  AuthenticatedStudioKpisRoute: typeof AuthenticatedStudioKpisRoute
  AuthenticatedStudioMarketingRoute: typeof AuthenticatedStudioMarketingRoute
  AuthenticatedStudioMontageRoute: typeof AuthenticatedStudioMontageRoute
  AuthenticatedStudioPhotographyRoute: typeof AuthenticatedStudioPhotographyRoute
  AuthenticatedStudioProgrammingRoute: typeof AuthenticatedStudioProgrammingRoute
  AuthenticatedStudioTasksRoute: typeof AuthenticatedStudioTasksRoute
  AuthenticatedStudioIndexRoute: typeof AuthenticatedStudioIndexRoute
}

const AuthenticatedStudioRouteRouteChildren: AuthenticatedStudioRouteRouteChildren =
  {
    AuthenticatedStudioAccountsRoute: AuthenticatedStudioAccountsRoute,
    AuthenticatedStudioBookingsRoute: AuthenticatedStudioBookingsRoute,
    AuthenticatedStudioCrmRoute: AuthenticatedStudioCrmRoute,
    AuthenticatedStudioDesignRoute: AuthenticatedStudioDesignRoute,
    AuthenticatedStudioKpisRoute: AuthenticatedStudioKpisRoute,
    AuthenticatedStudioMarketingRoute: AuthenticatedStudioMarketingRoute,
    AuthenticatedStudioMontageRoute: AuthenticatedStudioMontageRoute,
    AuthenticatedStudioPhotographyRoute: AuthenticatedStudioPhotographyRoute,
    AuthenticatedStudioProgrammingRoute: AuthenticatedStudioProgrammingRoute,
    AuthenticatedStudioTasksRoute: AuthenticatedStudioTasksRoute,
    AuthenticatedStudioIndexRoute: AuthenticatedStudioIndexRoute,
  }

const AuthenticatedStudioRouteRouteWithChildren =
  AuthenticatedStudioRouteRoute._addFileChildren(
    AuthenticatedStudioRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHubRouteRoute: typeof AuthenticatedHubRouteRouteWithChildren
  AuthenticatedAgencyRouteRoute: typeof AuthenticatedAgencyRouteRouteWithChildren
  AuthenticatedProductionRouteRoute: typeof AuthenticatedProductionRouteRouteWithChildren
  AuthenticatedReceptionRouteRoute: typeof AuthenticatedReceptionRouteRouteWithChildren
  AuthenticatedStudioRouteRoute: typeof AuthenticatedStudioRouteRouteWithChildren
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedProfileUserIdRoute: typeof AuthenticatedProfileUserIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHubRouteRoute: AuthenticatedHubRouteRouteWithChildren,
  AuthenticatedAgencyRouteRoute: AuthenticatedAgencyRouteRouteWithChildren,
  AuthenticatedProductionRouteRoute:
    AuthenticatedProductionRouteRouteWithChildren,
  AuthenticatedReceptionRouteRoute:
    AuthenticatedReceptionRouteRouteWithChildren,
  AuthenticatedStudioRouteRoute: AuthenticatedStudioRouteRouteWithChildren,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedProfileUserIdRoute: AuthenticatedProfileUserIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
